org 100h

.MODEL SMALL
.STACK 64

.DATA 
MESAJ DB 'I', 'S', 'M', 'A', 'I', 'L' 
.CODE
LEA DI,MESAJ ;MESAJ DÝZESININ ÝLK INDEX ADRESINI ALDIM
MOV CX,000CH
CLD  ;SAGDAN SOLA TARAMAK ICIN DI YI ARTIRDIM

MOV AL,'A'  
REPNE SCASB ;NE NOT EQUAL ESIT OLMAYANA KADAR DEVAM EDIYOR BULUNCA JUMP OLUCAK
JE BULDU

BULAMADI:
MOV AL,2 ;BULDUYSA AL 2 BULAMADIYSA 3 OLUYOR   
HLT

BULDU:
MOV AL,3
HLT

RET


